language: python
python:
    - "pypy"
    - "3.3"
    - "3.2"
    - "2.6"
    - "2.7"
    - "3.4"
    
install: python setup.py build

script: python setup.py test
#commit_container: vidyar/sample_push
build_image: drydock/u14pytpls:prod 
